#!/usr/bin/python2.7
# -*- coding: utf-8 -*-

from sys import exit,argv
import cProfile
from ptb_mol import TBController
from ptb_gui import MainView
from PyQt4.QtGui import QApplication

def main():
    """Main function

    Creates Backend, then parses arguments.
    If arguments match cli-interface, files will be parsed.
    If no cli-only behaviour is requested, gui will be started.
    """
    backend = TBController()

    if len(argv)==1:
        backend.newMol()
    elif argv[1] == '-h':
        print_help(backend,0)
    elif argv[1] in backend.cli_indict:
        for i in argv[2:]:
            backend.readFile(argv[1],i,'cli')
    else:
        print_help(backend,1)

    app = QApplication([])
    gui = MainView(backend)
    app.aboutToQuit.connect(gui.deleteLater)
    gui.loadView()
    exit(app.exec_())

def print_help(backend,err):
    print('PWToolBox usage:')
    print('ptb_main [OPTIONS]\n')
    print('No option given: start GUI\n')
    print('Options:')
    print('-h: print this help')
    for i in backend.cli_indict.items():
        print(i[0]+' [FILES]: '+i[1].__doc__.split('\n')[0])
    exit(err)

if __name__ == '__main__':
        main()
