#!/usr/bin/env python
# -*- coding: utf-8 -*-

from sys import exit,argv
from vipster import *
from vipster.ftypeplugins import _cli_indict as cli_indict
from PyQt4.QtGui import QApplication

def main():
    """Main function

    Parses molecules if present, then starts gui
    """
    if len(argv)==1:
        m=[Molecule(steps=1)]
        p=[]
    elif argv[1] == '-h':
        printHelp(0)
    elif argv[1].strip('-') in cli_indict:
        m=[];p=[]
        for i in argv[2:]:
            a,b=readFile(i,argv[1].strip('-'),'cli')
            m.append(a)
            if b:
                p.append(b)
    else:
        printHelp(2)

    launchVipster(m,p)

def printHelp(err):
    print('PWToolBox usage:')
    print('ptb_main [OPTIONS]\n')
    print('No option given: start GUI\n')
    print('Options:')
    print('-h: print this help')
    for i in ptb.cli_indict.items():
        print('-'+i[0]+' [FILES]: '+i[1].__doc__.split('\n')[0])
    exit(err)

if __name__ == '__main__':
        main()
